name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  flutter_svg: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/icon_2_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/cookies_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/dark_mode_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/group_3_x2.svg
  - assets/vectors/notification_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/battery_light_2_x2.svg
  - assets/vectors/image_2_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/network_signal_light_1_x2.svg
  - assets/vectors/wi_fi_signal_light_3_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/images/image_7.png
  - assets/images/image_4.png
  - assets/images/image_5.png
  - assets/images/image_2.png
  - assets/images/image_6.png
  - assets/vectors/shape_2_x2.svg
  - assets/images/image_4.png
  - assets/vectors/iconprofile_circled_x2.svg
  - assets/vectors/polygon_1_x2.svg
  - assets/images/rectangle_477.png
  - assets/images/rectangle_472.jpeg
  - assets/images/rectangle_476.jpeg
  - assets/images/edit.png
  - assets/images/rectangle_486.png
  - assets/images/rectangle_491.png
  - assets/images/rectangle_471.png
  - assets/images/rectangle_50.png
  - assets/images/rectangle_465.jpeg
  - assets/images/rectangle_463.jpeg
  - assets/images/rectangle_481.jpeg
  - assets/images/rectangle_484.jpeg
  - assets/images/rectangle_474.jpeg
  - assets/images/rectangle_48.jpeg
  - assets/images/rectangle_483.png
  - assets/images/rectangle_464.png
  - assets/images/rectangle_49.png
  - assets/images/rectangle_482.jpeg
  - assets/images/rectangle_46.png
  - assets/images/rectangle_461.jpeg
  - assets/images/rectangle_492.jpeg
  - assets/images/rectangle_485.png
  - assets/images/rectangle_473.png
  - assets/images/rectangle_494.jpeg
  - assets/images/rectangle_47.jpeg
  - assets/images/rectangle_493.jpeg
  - assets/images/rectangle_475.png
  - assets/images/rectangle_462.png
  - assets/vectors/container_x2.svg
  - assets/vectors/rectangle_4911_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/rectangle_495_x2.svg
  - assets/vectors/rectangle_4916_x2.svg
  - assets/vectors/view_1_x2.svg
  - assets/vectors/rectangle_498_x2.svg
  - assets/vectors/rectangle_4914_x2.svg
  - assets/vectors/rectangle_497_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/icon_10_x2.svg
  - assets/vectors/icon_7_x2.svg
  - assets/vectors/icon_8_x2.svg
  - assets/vectors/icon_4_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/icon_13_x2.svg
  - assets/vectors/icon_3_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/network_signal_light_2_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/image_6_x2.svg
  - assets/vectors/wi_fi_signal_light_4_x2.svg
  - assets/vectors/battery_light_x2.svg
  - assets/vectors/shape_18_x2.svg
  - assets/vectors/shape_19_x2.svg
  - assets/vectors/shape_13_x2.svg
  - assets/vectors/shape_7_x2.svg
  - assets/images/rectangle_6.png
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/network_signal_light_5_x2.svg
  - assets/vectors/wi_fi_signal_light_1_x2.svg
  - assets/vectors/battery_light_1_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/rectangle_499_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/icon_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/image_1_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/wi_fi_signal_light_2_x2.svg
  - assets/vectors/image_7_x2.svg
  - assets/vectors/network_signal_light_4_x2.svg
  - assets/vectors/battery_light_5_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/image_4_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/ming_cute_x2.svg
  - assets/vectors/mobile_signal_2_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/line_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/line_1_x2.svg
  - assets/vectors/icon_12_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/images/image_6.png
  - assets/images/image_2.png
  - assets/images/image_5.png
  - assets/images/image_1.png
  - assets/images/image_7.png
  - assets/images/image_3.png
  - assets/images/image_4.png
  - assets/vectors/shape_9_x2.svg
  - assets/vectors/shape_8_x2.svg
  - assets/vectors/shape_10_x2.svg
  - assets/images/image_10.png
  - assets/vectors/shape_x2.svg
  - assets/vectors/shape_11_x2.svg
  - assets/vectors/shape_5_x2.svg
  - assets/vectors/icon_11_x2.svg
  - assets/vectors/icon_9_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/icon_6_x2.svg
  - assets/vectors/icon_5_x2.svg
  - assets/vectors/icon_1_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/images/rectangle_50.png
  - assets/images/rectangle_462.png
  - assets/images/rectangle_49.png
  - assets/images/rectangle_485.png
  - assets/images/rectangle_483.png
  - assets/images/rectangle_474.jpeg
  - assets/images/rectangle_464.png
  - assets/images/rectangle_47.jpeg
  - assets/images/rectangle_491.png
  - assets/images/rectangle_494.jpeg
  - assets/images/rectangle_472.jpeg
  - assets/images/rectangle_482.jpeg
  - assets/images/rectangle_476.jpeg
  - assets/images/rectangle_484.jpeg
  - assets/images/edit.png
  - assets/images/rectangle_477.png
  - assets/images/rectangle_481.jpeg
  - assets/images/rectangle_492.jpeg
  - assets/images/rectangle_46.png
  - assets/images/rectangle_475.png
  - assets/images/rectangle_471.png
  - assets/images/rectangle_463.jpeg
  - assets/images/rectangle_461.jpeg
  - assets/images/rectangle_465.jpeg
  - assets/images/rectangle_486.png
  - assets/images/rectangle_48.jpeg
  - assets/images/rectangle_493.jpeg
  - assets/images/rectangle_473.png
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/square_x2.svg
  - assets/vectors/rectangle_4912_x2.svg
  - assets/vectors/rectangle_4913_x2.svg
  - assets/vectors/rectangle_4915_x2.svg
  - assets/vectors/rectangle_4917_x2.svg
  - assets/vectors/rectangle_496_x2.svg
  - assets/vectors/rectangle_4910_x2.svg
  - assets/vectors/view_11_x2.svg
  - assets/vectors/network_signal_light_3_x2.svg
  - assets/vectors/battery_light_4_x2.svg
  - assets/vectors/wi_fi_signal_light_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/image_9_x2.svg
  - assets/vectors/shape_6_x2.svg
  - assets/vectors/shape_12_x2.svg
  - assets/vectors/shape_4_x2.svg
  - assets/vectors/shape_15_x2.svg

